package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectivityChecker) DeepCopyInto(out *ConnectivityChecker) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectivityChecker.
func (in *ConnectivityChecker) DeepCopy() *ConnectivityChecker {
	if in == nil {
		return nil
	}
	out := new(ConnectivityChecker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectivityChecker) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectivityCheckerList) DeepCopyInto(out *ConnectivityCheckerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConnectivityChecker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectivityCheckerList.
func (in *ConnectivityCheckerList) DeepCopy() *ConnectivityCheckerList {
	if in == nil {
		return nil
	}
	out := new(ConnectivityCheckerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectivityCheckerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectivityCheckerSpec) DeepCopyInto(out *ConnectivityCheckerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectivityCheckerSpec.
func (in *ConnectivityCheckerSpec) DeepCopy() *ConnectivityCheckerSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectivityCheckerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectivityCheckerStatus) DeepCopyInto(out *ConnectivityCheckerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectivityCheckerStatus.
func (in *ConnectivityCheckerStatus) DeepCopy() *ConnectivityCheckerStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectivityCheckerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorPodsReporting) DeepCopyInto(out *ErrorPodsReporting) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectivityChecker.
func (in *ErrorPodsReporting) DeepCopy() *ErrorPodsReporting {
	if in == nil {
		return nil
	}
	out := new(ErrorPodsReporting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ErrorPodsReporting) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorPodsReportingList) DeepCopyInto(out *ErrorPodsReportingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ErrorPodsReporting, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectivityCheckerList.
func (in *ErrorPodsReportingList) DeepCopy() *ErrorPodsReportingList {
	if in == nil {
		return nil
	}
	out := new(ErrorPodsReportingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ErrorPodsReportingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorPodsReportingSpec) DeepCopyInto(out *ErrorPodsReportingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectivityCheckerSpec.
func (in *ErrorPodsReportingSpec) DeepCopy() *ErrorPodsReportingSpec {
	if in == nil {
		return nil
	}
	out := new(ErrorPodsReportingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorPodsReportingStatus) DeepCopyInto(out *ErrorPodsReportingStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorPodsReportingStatus.
func (in *ErrorPodsReportingStatus) DeepCopy() *ErrorPodsReportingStatus {
	if in == nil {
		return nil
	}
	out := new(ErrorPodsReportingStatus)
	in.DeepCopyInto(out)
	return out
}
